### ISSUE TITLE
Encoding non-Latin characters txt files

### ISSUE THREAD

**Issue by CVidalG** [PonteIneptique/medievalto-to-tei#1]
Hi,

Example of an output:

`b'#\xd4\xb5\xd6\x80\xd5\xa2 \xd5\xb3\xd5\xa1\xd5\xb7\xd5\xa1\xd6\x80\xd5\xa1\xd5\xb6\xd5\xab \xd5\xa3\xd5\xa1\xd5\xb6\xd5\xb1\xd5\xa1\xd5\xba\xd5\xa1\xd5\xb0\xd5\xb8\xd6\x82\xd5\xb0\xd5\xab\xd5\xb6 \xd5\xbe\xd5\xa5\xd6\x80\xd5\xa1\xd5\xa4\xd5\xa1\xd6\x80\xd5\xb1\xd6\x80\xd5\xa5\xd6\x81
 \xd5\xb0\xd5\xab\xd5\xb6\xd5\xa3-`

[Archive.zip](https://github.com/PonteIneptique/medievalto-to-tei/files/8496009/Archive.zip)

**Comment by CVidalG** [comment]
Hi,

Thanks for the fix ! But when trying to upload the same Archive.zip file after pulling your update, I have the following error : 

```
Traceback (most recent call last):
  File "/Users/miniconda3/envs/medievalto/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/miniconda3/envs/medievalto/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/miniconda3/envs/medievalto/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/miniconda3/envs/medievalto/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/medievalto-to-tei/app/routes.py", line 26, in docs_add
    for file, content in parse_zip(request.files["docZip"]):
  File "/Users/medievalto-to-tei/app/parser.py", line 38, in parse_zip
    yield file, f.read().decode("UTF-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 45: invalid start byte
```

**Comment by PonteIneptique** [comment]
Tracked the bug: it's a MacOS induced bug because of `__MACOSX/._hye-1.txt`

**Comment by PonteIneptique** [comment]
Should be fixed
