### ISSUE TITLE
XML on MacOs

### ISSUE THREAD

**Issue by CVidalG** [PonteIneptique/medievalto-to-tei#2]
Hi,

With zip file with ALTO XML and images:

```
[2022-04-15 14:45:08,742] ERROR in app: Exception on /documents/add [POST]
Traceback (most recent call last):
  File "/Users/miniconda3/envs/medievalto/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/miniconda3/envs/medievalto/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/miniconda3/envs/medievalto/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/miniconda3/envs/medievalto/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/medievalto-to-tei/app/routes.py", line 24, in docs_add
    for file, content in parse_zip(request.files["docZip"]):
  File "/Users/medievalto-to-tei/app/parser.py", line 36, in parse_zip
    for string in ET.parse(f).findall("//{*}TextLine/{*}String")
  File "src/lxml/etree.pyx", line 3536, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1897, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1917, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1811, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1201, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "/Users/medievalto-to-tei/__MACOSX/Arras-861/._056r.xml", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1
```

**Comment by PonteIneptique** [comment]
This has been fixed :)
